print("Nama         : Kavita Lailia Ina Zahra")
print("NIM          : I0322064")
print("Kota Asal    : Magelang")
print("=========================================")
print("Nama lengkap saya Kavita Lailia Ina Zahra dan biasa dipanggil Kavita.")
print("Saya berasal dari Kota Magelang yang terkenal dengan bangunan bernama Candi Borobudur.")
print("Candi Borobudur merupakan candi yang termasuk dalam 7 keajaiban dunia.")
print("Selain itu Magelang memiliki makanan khas yang bernama Gethuk.")
print("=========================================")
print("Harapan saya sebagai lulusan Teknik Industri adalah bisa menerapkan ilmu yang saya dapat diperkuliahan, bekerja diperusahaan terkenal, dan memiliki penghasilan tinggi.")
